// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetContentData, GetContentResponse, GetContentError, GetContent20Data, GetContent20Response, GetContent20Error, GetContentItemData, GetContentItemResponse, GetContentItemError, GetContentItemByPathData, GetContentItemByPathResponse, GetContentItemByPathError, GetContentItemByPath20Data, GetContentItemByPath20Response, GetContentItemByPath20Error, GetContentItemByIdData, GetContentItemByIdResponse, GetContentItemByIdError, GetContentItemById20Data, GetContentItemById20Response, GetContentItemById20Error, GetContentItems20Data, GetContentItems20Response, GetContentItems20Error, GetMediaData, GetMediaResponse, GetMediaError, GetMedia20Data, GetMedia20Response, GetMedia20Error, GetMediaItemData, GetMediaItemResponse, GetMediaItemByPathData, GetMediaItemByPathResponse, GetMediaItemByPathError, GetMediaItemByPath20Data, GetMediaItemByPath20Response, GetMediaItemByPath20Error, GetMediaItemByIdData, GetMediaItemByIdResponse, GetMediaItemByIdError, GetMediaItemById20Data, GetMediaItemById20Response, GetMediaItemById20Error, GetMediaItems20Data, GetMediaItems20Response } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class ContentService {
    /**
     * @deprecated
     */
    public static getContent<ThrowOnError extends boolean = false>(options?: Options<GetContentData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetContentResponse, GetContentError, ThrowOnError>({
            url: '/umbraco/delivery/api/v1/content',
            ...options
        });
    }
    
    public static getContent20<ThrowOnError extends boolean = false>(options?: Options<GetContent20Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetContent20Response, GetContent20Error, ThrowOnError>({
            url: '/umbraco/delivery/api/v2/content',
            ...options
        });
    }
    
    /**
     * @deprecated
     */
    public static getContentItem<ThrowOnError extends boolean = false>(options?: Options<GetContentItemData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetContentItemResponse, GetContentItemError, ThrowOnError>({
            url: '/umbraco/delivery/api/v1/content/item',
            ...options
        });
    }
    
    /**
     * @deprecated
     */
    public static getContentItemByPath<ThrowOnError extends boolean = false>(options: Options<GetContentItemByPathData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetContentItemByPathResponse, GetContentItemByPathError, ThrowOnError>({
            url: '/umbraco/delivery/api/v1/content/item/{path}',
            ...options
        });
    }
    
    public static getContentItemByPath20<ThrowOnError extends boolean = false>(options: Options<GetContentItemByPath20Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetContentItemByPath20Response, GetContentItemByPath20Error, ThrowOnError>({
            url: '/umbraco/delivery/api/v2/content/item/{path}',
            ...options
        });
    }
    
    /**
     * @deprecated
     */
    public static getContentItemById<ThrowOnError extends boolean = false>(options: Options<GetContentItemByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetContentItemByIdResponse, GetContentItemByIdError, ThrowOnError>({
            url: '/umbraco/delivery/api/v1/content/item/{id}',
            ...options
        });
    }
    
    public static getContentItemById20<ThrowOnError extends boolean = false>(options: Options<GetContentItemById20Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetContentItemById20Response, GetContentItemById20Error, ThrowOnError>({
            url: '/umbraco/delivery/api/v2/content/item/{id}',
            ...options
        });
    }
    
    public static getContentItems20<ThrowOnError extends boolean = false>(options?: Options<GetContentItems20Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetContentItems20Response, GetContentItems20Error, ThrowOnError>({
            url: '/umbraco/delivery/api/v2/content/items',
            ...options
        });
    }
    
}

export class MediaService {
    /**
     * @deprecated
     */
    public static getMedia<ThrowOnError extends boolean = false>(options?: Options<GetMediaData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetMediaResponse, GetMediaError, ThrowOnError>({
            url: '/umbraco/delivery/api/v1/media',
            ...options
        });
    }
    
    public static getMedia20<ThrowOnError extends boolean = false>(options?: Options<GetMedia20Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetMedia20Response, GetMedia20Error, ThrowOnError>({
            url: '/umbraco/delivery/api/v2/media',
            ...options
        });
    }
    
    /**
     * @deprecated
     */
    public static getMediaItem<ThrowOnError extends boolean = false>(options?: Options<GetMediaItemData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetMediaItemResponse, unknown, ThrowOnError>({
            url: '/umbraco/delivery/api/v1/media/item',
            ...options
        });
    }
    
    /**
     * @deprecated
     */
    public static getMediaItemByPath<ThrowOnError extends boolean = false>(options: Options<GetMediaItemByPathData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetMediaItemByPathResponse, GetMediaItemByPathError, ThrowOnError>({
            url: '/umbraco/delivery/api/v1/media/item/{path}',
            ...options
        });
    }
    
    public static getMediaItemByPath20<ThrowOnError extends boolean = false>(options: Options<GetMediaItemByPath20Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetMediaItemByPath20Response, GetMediaItemByPath20Error, ThrowOnError>({
            url: '/umbraco/delivery/api/v2/media/item/{path}',
            ...options
        });
    }
    
    /**
     * @deprecated
     */
    public static getMediaItemById<ThrowOnError extends boolean = false>(options: Options<GetMediaItemByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetMediaItemByIdResponse, GetMediaItemByIdError, ThrowOnError>({
            url: '/umbraco/delivery/api/v1/media/item/{id}',
            ...options
        });
    }
    
    public static getMediaItemById20<ThrowOnError extends boolean = false>(options: Options<GetMediaItemById20Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetMediaItemById20Response, GetMediaItemById20Error, ThrowOnError>({
            url: '/umbraco/delivery/api/v2/media/item/{id}',
            ...options
        });
    }
    
    public static getMediaItems20<ThrowOnError extends boolean = false>(options?: Options<GetMediaItems20Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetMediaItems20Response, unknown, ThrowOnError>({
            url: '/umbraco/delivery/api/v2/media/items',
            ...options
        });
    }
    
}